POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "6419b49e09dfe3eefb495228"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

###
GET  http://localhost:8081/rating/getAll
Content-Type: application/json

###
GET  http://localhost:8081/comment/getAll
Content-Type: application/json

###
POST http://localhost:8081/comment/add
Content-Type: application/json 

{
    "username" : "ArrivoUser",
    "stationName" : "Aberdeen Ave - Harvard Station",
    "comment" : "this station slaps"
}

###
POST http://localhost:8081/comment/editComment
Content-Type: application/json

{
    "_id" : "643e98aaf948950b01f94362",
    "username" : "ArrivoUser",
    "stationName" : "Alewife - Kendall/MIT",
    "comment" : "This comment has been removed by the Comment Police"
}

###
POST http://localhost:8081/comment/deleteCommentById
Content-Type: application/json

{
    "commentId" : "6442db018102d3b4d7c127f6"
}

###
GET http://localhost:8081/comment/getCommentById
Content-Type: application/json

{
    "commentId" : "643e98aaf948950b01f94362"
}

###
POST http://localhost:8081/comment/deleteAll